### ISSUE TITLE
数据集的细节

### ISSUE THREAD

**Issue by mengzixing** [thunlp/LegalPLMs#2]
代码里没有给出训练数据，请问有没有train_files/valid_files的demo数据或者数据格式说明？

**Comment by HongliMeng** [comment]
请问有没有demo呀

**Comment by xcjthu** [comment]
Sorry for missing the information. We utilize the tools developed by NVIDIA to store the pre-training data (specifically, in 
https://github.com/NVIDIA/Megatron-LM/blob/main/tools/preprocess_data.py). We should first convert textual data into token ids.
