### ISSUE TITLE
Use lawformer with transformers

### ISSUE THREAD

**Issue by maicai** [thunlp/LegalPLMs#3]
Hey！If I want to use lawformer with transformers to calculate case similarity, what should I do? could you share some demo?

**Comment by Alice1222myy** [comment]
> Hey！If I want to use lawformer with transformers to calculate case similarity, what should I do? could you share some demo?

I have the same question with you. Have you got any solutions?

**Comment by xcjthu** [comment]
In the paper, we concate the query case and candidate case together, and feed the representation of [CLS] tokens to a MLP layer to calculate the similarity scores. By the way, as the global attention requires massive GPU memories, we can only train the model on V100 GPUs.

**Comment by lkywlp99** [comment]
> > Hey！If I want to use lawformer with transformers to calculate case similarity, what should I do? could you share some demo?
> Hello ,have  you solve the problem yet? I tried the model author provied,only get the output of Lawformer which is a LongformerBasemodeOutputWithPooling ,but I have no idea about how to finish the  downstream tasks,such as legal judgement prediction.
> I have the same question with you. Have you got any solutions?

**Comment by milktean** [comment]
Hello ,have you solve the problem yet? I tried the model author provied,only get the output of Lawformer which is a LongformerBasemodeOutputWithPooling ,but I have no idea about how to finish the downstream tasks,such as legal judgement prediction

**Comment by milktean** [comment]
> In the paper, we concate the query case and candidate case together, and feed the representation of [CLS] tokens to a MLP layer to calculate the similarity scores. By the way, as the global attention requires massive GPU memories, we can only train the model on V100 GPUs.

Can you share some demos so we can reproduce the results in the paper you publish.
