### ISSUE TITLE
使用transformers做类案检索时，按照论文介绍复现，始终报RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by Alice1222myy** [thunlp/LegalPLMs#4]
您好，我阅读了lawformer的原论文，并按照legal case retrieval部分 Implementation Details 的介绍进行文本二分类任务。使用`model = BertForSequenceClassification.from_pretrained("thunlp/Lawformer", output_attentions=False, output_hidden_states=False)
`调用Lawformer模型，将query长度限制在509，candidates长度限定在3072，训练时即使batch_size取1，也会报`RuntimeError: CUDA out of memory.`的错误，不知如何解决。

还想请教一下，如何设定global attention呢

**Comment by xcjthu** [comment]
这是显卡配置问题，您可以考虑使用更大显存的GPU

**Comment by LL020202** [comment]
@Alice1222myy 您好，类案检索还在做吗
