### ISSUE TITLE
如何设置全局注意力？

### ISSUE THREAD

**Issue by zhujlfree** [thunlp/LegalPLMs#7]
你好，想请教一个问题可以吗？ 
在论文类案检索部分介绍了 选择查询案例的所有tokens做全局注意力，请问一下 在调用您提供的checkpoint进行微调的时候，具体是怎么设置这个全局注意力呢？
我使用下面的代码来调用模型：
tokenizer = AutoTokenizer.from_pretrained("hfl/chinese-roberta-wwm-ext")
model = AutoModel.from_pretrained("xcjthu/Lawformer")
text_a = "任某提起诉讼，请求判令解除婚姻关系并对夫妻共同财产进行分割。"
text_b = "任某提起诉讼，请求判令解除婚姻关系并对夫妻共同财产进行分割。"
inputs = tokenizer(text_a,text_b,return_tensors="pt") 
outputs= model(**inputs)

**Comment by milktean** [comment]
请问要怎么样拿这里的outputs来做后面的任务呢
